# Generated by Django 5.1.2 on 2024-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymjao_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, unique=True)),
                ('user_exercise', models.ManyToManyField(related_name='days', to='gymjao_app.userexercise')),
            ],
        ),
    ]
